# Generated by Django 5.2.8 on 2025-11-22 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_payment', models.CharField(choices=[('inscription', 'Inscription'), ('mensuality', 'Mensualité'), ('cantine', 'Cantine'), ('transport', 'Transport')], max_length=20)),
                ('method', models.CharField(choices=[('orange', 'Orange Money'), ('moov', 'Moov Money'), ('wave', 'Wave'), ('cash', 'Cash')], max_length=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-paid_at'],
            },
        ),
    ]
