# Generated by Django 5.2.8 on 2025-11-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_receipt_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('last', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
