# Generated by Django 5.2.8 on 2025-11-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='coefficient',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='matiere',
            name='cycle',
            field=models.CharField(choices=[('jardin', 'Jardin / Maternelle'), ('primaire', 'Primaire 1-6'), ('secondaire', 'Secondaire 7-9'), ('lycee', 'Lycée 10-12')], default='primaire', max_length=20),
        ),
    ]
