# Generated by Django 5.2.8 on 2025-11-23 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_parent_user_alter_student_user_and_more'),
        ('classes', '0002_matiere_coefficient_matiere_cycle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matiere',
            options={'ordering': ['nom'], 'verbose_name': 'Matière', 'verbose_name_plural': 'Matières'},
        ),
        migrations.AddField(
            model_name='classe',
            name='eleves',
            field=models.ManyToManyField(blank=True, related_name='classes', to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='enseignants',
            field=models.ManyToManyField(blank=True, related_name='classes', to='accounts.teacher'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='matieres',
            field=models.ManyToManyField(blank=True, related_name='classes', to='classes.matiere'),
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps', to='classes.classe'),
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplois_du_temps', to='accounts.teacher'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='cycle',
            field=models.CharField(choices=[('primaire', 'Primaire 1-6'), ('secondaire', 'Secondaire 7-9'), ('lycee', 'Lycée 10-12')], default='primaire', max_length=20),
        ),
    ]
