# Generated by Django 5.2.8 on 2025-11-22 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('classes', '0002_matiere_coefficient_matiere_cycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('trimester', models.IntegerField(choices=[(1, '1er trimestre'), (2, '2ème trimestre'), (3, '3ème trimestre')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.CharField(choices=[('primaire', 'Primaire 1-6'), ('secondaire', 'Secondaire 7-9'), ('lycee', 'Lycée 10-12')], max_length=20)),
                ('type_eval', models.CharField(choices=[('CC', 'Contrôle Continu'), ('EX', 'Examen')], default='CC', max_length=2)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.matiere')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'matiere', 'trimester', 'type_eval')},
            },
        ),
    ]
